[project]
name = "uv-with-fast"
version = "0.1.0"
description = "This is the fastapi boiler plate on docker using uv "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.7",
    "uvicorn>=0.34.0",
]
